const ENV_FLAGS = {
    FAST_AS_FUCK_TRANSITIONS: true,
    CONTROLLER_DISABLED: false,
    DO_STEAM_SETUP: false,
    MUSIC_FILE_FORMAT: "ogg",
    BATTLE_RENDERER: false,
    NO_SONOGRAPH_WARNING: false,
    ELF_PLAYER_HACK: false,
    MOVEMENT_FRAME_WARNING: true,
    CONVOY_TRACE: true
}
