const CharacterData = {
    Makers: {
        "jim":              "default",
        "frogert":          "default",
        "wimpy-red-elf":    "elf",
        "ice-man":          "default",
        "chili-wife":       "default",
        "chili":            "default",
        "tree-lee":         "default",
        "jam":              "default",
        "wizard-elf":       "elf",
        "tiny-arm-elf":     "elf",
        "wimpy-green-elf":  "elf",
        "concealed-spy":    "elf"
    },
    Colors: {
        "jim":              "blue",
        "frogert":          "green",
        "wimpy-red-elf":    "red",
        "red-elfette":      "red",
        "boney-elf":        "deeppink",
        "wizard-elf":       "blueviolet",
        "headless-elf":     "darkorange",
        "jester-elf":       "goldenrod",
        "mascara":          "deeppink",
        "burr":             "darkorange",
        "shiver":           "blueviolet",
        "ice-man":          "cyan",
        "tree-lee":         "blueviolet",
        "chili":            "darkorange",
        "chili-wife":       "deeppink",
        "jam":              "blue",
        "boxy":             "blueviolet",
        "louis":            "green",
        "wizard-elf":       "blueviolet",
        "tiny-arm-elf":     "cyan",
        "wimpy-green-elf":  "green",
        "rock-elf-spy":     "red",
        "enigma":           "red",
        "concealed-spy":    "black" 
    },
    DisplayNames: {
        "jim":              "Jim",
        "frogert":          "Frogert",
        "wimpy-red-elf":    "Wimpy Red Elf",
        "red-elfette":      "Red Elfette",
        "boney-elf":        "Boney Elf",
        "wizard-elf":       "Wizard Elf",
        "headless-elf":     "Headless Elf",
        "jester-elf":       "Jester Elf",
        "mascara":          "Mascara",
        "burr":             "Burr",
        "shiver":           "Shiver",
        "ice-man":          "Ice Man",
        "tree-lee":         "Tree Lee",
        "chili":            "Chili",
        "chili-wife":       "Chillene",
        "jam":              "Jam",
        "boxy":             "Boxy",
        "louis":            "Louis",
        "wizard-elf":       "Wizard Elf",
        "tiny-arm-elf":     "Tiny Arm Elf",
        "wimpy-green-elf":  "Wimpy Green Elf",
        "rock-elf-spy":     "Rock Elf Spy",
        "enigma":           "Enigma",
        "concealed-spy":    "Bob"
    },
    SpriteLookup: {
        "elf-guard-1": "elf-guard",
        "elf-guard-2": "elf-guard",
        "concealed-spy": "spy/default"
    }
}
