const stringLookup = {
    bookcase_1: "There's a lot of books on this shelf.",
    bed_1: "A sleeping bag on a hardwood floor, a fine luxury.",
    bookcase_2: "Lots of books here... A lot of them seem to mention some kind of card game?",
    bookcase_3: "This bookcase demonstrates that it's okay to be small. Way to go bookcase!",
    table_1: "These plastic, foldable tables have seen a lot of life. Are they for parties?",
    table_2: "These tables are pretty much everywhere.",
    counter_1: "This must be a kitchen... Seems to be missing a few things, though.",
    counter_2: "This is the cleanest kitchen you've seen in your entire life.",
    sink_1: "It's important to wash your hands!",
    toilet_1: "It's important to use toilets!",
    bathtub_1: "It's important to wash... yourself.",
    bookcase_4: "This bookcase doesn't have very many books on it.",
    bookcase_5_1: "This bookcase has a few intersting books on it.",
    bookcase_5_2: "One book is called 'the cat lady manifesto'",
    bookcase_5_3: "ȸIf I loved my children as much as I love my cats, I'd have children.ȸ",
    bookcase_6_1: "This bookcase is trying to be an edgy reflection of society.",
    bookcase_6_2: "Is it working?",
    bookcase_7_1: "This bookcase seems to be more inappropriate than the other bookcases.",
    bookcase_7_2: "Hey... What're you wearing?",
    couch_1: "This couch looks too clean to sit on. Who gets a white couch anyways?",
    jims_journey: "That was quite the journey... You may use the door, now.",
    jims_kink: "If you whisper something in my right ear I'll get out of your way.",
    jims_intrigue: "Oh. My. I'll be getting out of your way, now.",
    jims_postop: "Let's stay in touch. Hehe.",
    sleepingbag_1: "Hmm... Sleeping bags seem to be in style in this town.",
    bookcase_8_1: "There's not many books on this shelf, but there are a few interesting ones.",
    bookcase_8_2: "ȸOwning Two Pieces of Furniture for Dummiesȸ",
    bookcase_8_3: "It seems to be a book about minimalism.",
    sleepingbag_2: "Whoever lives here also has a sleeping bag. Do they only come in one color?",
    rudetable: "Someone didn't bring the chair back to the table. How rude!",
    dryer_1: "What kind of a heathen has their dryer on the left?",
    washer_1: "The washer being on the right is making you very uncomfortable.",
    sb_1: "A lot of people must sleep here.",
    sb_2: "This sleeping bag doesn't want to be bothered.",
    sb_3: "This sleeping bag is upset with the other sleeping bags.",
    sb_4: "Who would want to sleep this close to other people?",
    emptyshelf: "The books appear to have slipped into another dimension.",
    bookcase_9_1: "There's a notecard taped to this shelf.",
    bookcase_9_2: "'Adults only'",
    bookcase_9_3: "Hmm... this might be interesting.",
    bookcase_9_4_1: "Ew. There's more important things you should be doing than reading someone else's smut.",
    bookcase_9_4_2: "Ah, I see. Saving yourself for marriage.",
    longtable: "This table is long, yet, you can't help but feel disappointed by it.",
    indoor_tree: "An indoor tree? Finally, something unique in one of these houses.",
    nice_envo: "There's a nice atmosphere to do things at this table.",
    bright_idea: "What a bright idea putting a lamp next to two windows.",
    couch_2: "The couch has some light stains on it.",
    couch_3: "The couch is so bright it's hard to look at.",
    likes_books_1: "Wow. this person sure likes books.",
    likes_books_2: "You can't grab any books or else the whole house might fall apart.",
    bathtub_getaway: "This is clearly a room of luxury.",
    french_rev_1: "There's a book sticking out from under the pillow.",
    french_rev_2: "It says something about the French revolution.",
    sat_lt_1: "This lighting is satisfying.",
    sat_lt_1: "Perfectly symmetrical, as all things should be.",
    jims_help_1: "Oh. Hi there.",
    jims_help_2: "If you want to talk with me, come over to me and use your mouth.",
    jims_help_3: "...",
    jims_help_4: "Oh. You don't know how to use your mouth?",
    jims_help_5: "...",
    jims_help_6: "Well, this is awkward.",
    jims_help_7: "Give me a second.",
    jims_help_8: "...",
    jims_help_9: "What? You already figured it out?",
    jims_help_10: "Well, it's nice to meet you. My name is Jim.",
    you_can_never_leave: "You can't leave ȹTumble Townȹ yet! You have important things to do!",
    stranger_danger: "Ahh! Stranger danger! Get away from me!",
    AUTO_1: "You should probably go check if that frog you scared is okay first.",
    AUTO_2: "Who is it?",
    AUTO_3: "Mom..? You sound different. Did you start drinking again?",
    AUTO_4: "Ohhh, Jim? Long time no see. Come on in!",
    AUTO_5: "Sorry 'not really sure', but I can't just let strangers in without a warrant.",
    AUTO_6: "Uhh, who's there?",
    AUTO_7: "Mom..? Mom who?",
    AUTO_8: "My neighbor who?",
    AUTO_9: "Frogert. Huh. Are you my clone? Frogert who?",
    AUTO_10: "Only if you ask nicely.",
    AUTO_11: "Please leave now. I don't have time for your rudeness.",
    AUTO_12: "See, that's better. You may come in, now.",
    AUTO_13: "Oh. Okay. Bye then.",
    AUTO_14: "What makes you think you can just barge on in here?",
    AUTO_15: "What do you want to say?",
    AUTO_16: "Yeah, right. 'Boldness'",
    AUTO_17: "You know who else is bold? Crazy people.",
    AUTO_18: "Try again next time. I've got enough of my own crazy in here.",
    AUTO_19: "Alright. That's fair.",
    AUTO_20: "You've got places to be, I get it.",
    AUTO_21: "Really, I do.",
    AUTO_22: "You can come in, now.",
    AUTO_23: "Really? A key to the city?",
    AUTO_24: "What's the mayors name, then?",
    AUTO_25: "You're not the mayor...",
    AUTO_26: "John Smith? John Smith at yahoo.com?",
    AUTO_27: "Well you must have important things to do, John Smith.",
    AUTO_28: "I'll let you be on your way, now.",
    AUTO_29: "I only let trusted people in my home.",
    AUTO_30: "Hmm. You don't sound like the mayor.",
    AUTO_31: "In fact, we don't even have a mayor. We just have town meetings.",
    AUTO_32: "Anyhow, I don't let liars into my home.",
    AUTO_33: "Alright, look wise guy. I know you're not Frogert.",
    AUTO_34: "And I know you think you're sooooooo funny, but I'm not going to let you in my home just because you can make a decent joke.",
    AUTO_35: "Oh. You're that creep that lives next door.",
    AUTO_36: "I would prefer you not coming in, it took me a week to get the stench of your booze out of here last time.",
    AUTO_37: "Come back when you've laid off the booze.",
    AUTO_38: "Wow. That's a reallllly good joke... *cough*",
    AUTO_39: "If you want in my house you're gonna have to do better than that.",
    AUTO_40: "Well, now is not a good time, mom. I'm hiding from that stranger outside. You should look out.",
    AUTO_41: "Oh! Before you go, could you go and meet your neighbor? He doesn't have a lot of friends. Thanks.",
    AUTO_42: "Go get me some beer, dude. Ah, I mean, uh, 'friend'.",
    AUTO_43: "f- friend? After everything we've been through together? What are you, crazy!",
    AUTO_44: "What? It's only been about a minute?",
    AUTO_45: "...",
    AUTO_46: "Well, at any rate, I suppose. maybe... just maybe, we could be friends.",
    AUTO_47: "... just don't touch me, please.",
    AUTO_48: "Okay. Now that we're 'friends', why don't you be a pal and get me a beer from the ȴTavern?ȴ",
    AUTO_49: "Follow the path and keep north, it's right at the base of ȴGreat Lake Tumble.ȴ",
    AUTO_50: "And don't take too long, I want it to be cold when you bring it back.",
    AUTO_51: "Hey! You're the same stranger from outside!",
    AUTO_52: "You tricked me!",
    AUTO_53: "Uh. Hi. I'm still not okay with you coming in here on false pretenses.",
    AUTO_54: "Explain yourself.",
    AUTO_55: "...",
    AUTO_56: "Well. I can't argue with that logic.",
    AUTO_57: "Honestly? That is sooo relatable.",
    AUTO_58: "I feel like I understand everything we've been through together so much better now.",
    AUTO_59: "I think we will be the best of pals",
    AUTO_60: "Great pals.",
    AUTO_61: "Pals forever.",
    AUTO_62: "Pals who definitely won't betray each other.",
    AUTO_63: "Ever.",
    AUTO_64: "You should be a good friend and get a beer from the ȴTavernȴ for Frogert. You can go here later.",
    AUTO_65: "You've helped us poor helpless ice cream cones get our booze fix, so consider this a token of our gratitude.",
    AUTO_66: "Thanks again, bro. Now leave us to drink these beers in peace.",
    AUTO_67: "Hey, you already gave me a beer. Burr is waiting his still.",
    AUTO_68: "Why did you give Burr a beer first? Go get another one!",
    AUTO_69: "Hey, did you hear that conversation? Wanna be a pal? Go get us some beers.",
    AUTO_70: "Thank you so much for being a pal and getting us these beers! We are in your debt forever.",
    AUTO_71: "I am so lucky that you gave me a beer first, but don't forget Shiver!",
    AUTO_72: "You gave Shiver a beer but what about meeee? Go get another one!",
    AUTO_73: "I would really appreciate you going and getting us some beers. I don't have much to give you but I will spread good word about you.",
    AUTO_74: "Hello, how can I help you?",
    AUTO_75: "Ahh. Beer. Now THAT I can help you with.",
    AUTO_76: "You still have the other beer I gave you. How about drinking that one first?",
    AUTO_77: "Do you have a drinking problem too? This is going on your tab.",
    AUTO_78: "What happened to the other beer I gave you?",
    AUTO_79: "...",
    AUTO_80: "I swear to god...",
    AUTO_81: "...",
    AUTO_82: "You gave it to the chair, didn't you?",
    AUTO_83: "Just take another one. It's going on your tab.",
    AUTO_84: "Alright, coming right up. I have to ask though.. This isn't for a chair, right?",
    AUTO_85: "Okay! Great. Uh, don't ask. There has just been some... 'events' in the past and I have to make sure the chairs stay sober.",
    AUTO_86: "No! No no no a million times NO!",
    AUTO_87: "AHHHHHHHHHHHHHHHHH!",
    AUTO_88: "You're not allowed to give the chairs beer. EVER. No exceptions.",
    AUTO_89: "Fine, you're right. It's none of my business what you do with your alchohol after you leave this counter!",
    AUTO_90: "I'm totally sure you'll be responsible and not give it to any chairs.",
    AUTO_91: "Okay, since we're friends, this is on the house!",
    AUTO_92: "Alright, I'll put this on your tab.",
    AUTO_93: "I would love to do that for you but I don't have hands. Or arms. Or shakers.",
    AUTO_94: "Uhhh. That's not the right kind of poison.",
    AUTO_95: "Are you feeling insecure? I thought we already established our friendship.",
    AUTO_96: "Friends? I barely just met you. Well whatever. You only live once, right?",
    AUTO_97: "You seem cool, so, all booze is on the house!",
    AUTO_98: "Ah. Jeez. Sorry, but our policy doesn't cover that. I am an ice cream cone.",
    AUTO_99: "Look, I'd love to help you with all your problems but I am a bartender, not a miracle worker.",
    AUTO_100: "The most I can do for you is get you a beer.",
    AUTO_101: "You brought me MOREEEEEE????",
    AUTO_102: "SHUT IT NARRATOR. FEEED MEEEEE.",
    AUTO_103: "ReEeeEEeEEEeeEeeEEeEEEee",
    AUTO_104: "HAHAHAHA. YOU IDIOT.",
    AUTO_105: "reeeeeEEEEEEEEEEEEE",
    AUTO_106: "REEEEEEEEEEEEEEEEEEEEEEE",
    AUTO_107: "Hey. If you bring me back a beer, I'll let you in on a secret.",
    AUTO_108: "Rule number 1 of talking to chairs- Uh, wait. How are you talking to me? I'm a chair!",
    AUTO_109: "GET AWAY FROM ME, WITCH!",
    AUTO_110: "When people come here they never sit at this tables. I blame the chairs. They're just so...",
    AUTO_111: "frigid. hehe.",
    AUTO_112: "...",
    AUTO_113: "Okaaay, fine. Maaaybe it's my puns.",
    AUTO_114: "Hey. You should sit on me. I won't bite. I promise.",
    AUTO_115: "What? You don't believe me because I said that in the first place?",
    AUTO_116: "And I'm not making it better for myself?",
    AUTO_117: "Look out for my brother. He gets nervous around new people.",
    AUTO_118: "Hands off please. I just got washed.",
    AUTO_119: "That chair around the corner has a huge booze problem. It was quite the scene last time.",
    AUTO_120: "It gets lonely over here next to the endless void.",
    AUTO_121: "Man, it would be real convenient if someone came in here right now that could go get us more beers.",
    AUTO_122: "You're so right dude. I would kill for another beer right now.",
    AUTO_123: "Yeah, but it's just a pipe dream. The odds of someone walking in here right now and hearing this exact conversation are so low.",
    AUTO_124: "You need to get that beer back to Frogert while it's still cold. Just like a friend should.",
    AUTO_125: "Aweee yeah! What a boss!",
    AUTO_126: "Hey! Thanks a lot dude.",
    AUTO_127: "You're awesome! You got us beers out of the goodness of your heart! Come over here, I've got something for your troubles.",
    AUTO_128: "... alright. You should go, now.",
    AUTO_129: "...",
    AUTO_130: "This isn't poison is it?",
    AUTO_131: "Well, that's a risk I'm willing to take. I'm just sooo thirsty.",
    AUTO_132: "Ahhhhhhhhh",
    AUTO_133: "That hit the spot.",
    AUTO_134: "Thanks again, 'friend.'",
    AUTO_135: "Speaking of friends, you should probably go meet more members of the town, don't you think?",
    AUTO_136: "My other next door neighbor besides you and Jim is ȴIce Man.ȴ He knows a lot about fighting or something.",
    AUTO_137: "Alright. Now leave me in peace to get about as drunk as possible for a frog.",
    AUTO_138: "Did you met teh ȴIce Manȴ yeh? i promes 'es not es intimidorting as he sound.",
    AUTO_139: "Wow! You actually came back with beer. I wasn't so sure that you would.",
    AUTO_140: "... it took long enough.",
    AUTO_141: "Now, please bring it over here. I'm so parched I can barely move."
}
const strings = stringLookup;
const getString = function(ID) {
    return stringLookup[ID];
}
const getSyllableMap = function(word) {
    word = word.toLowerCase();
    return wordSyllableMaps[word];
}
