"use strict";
leftBumperCode = {code:"LeftBumper"};
rightBumperCode = {code:"RightBumper"};
aButtonCode = {code:"Enter"};
yButtonCode = {code:"KeyP"};
bButtonCode = {code:"KeyZ"};
upButtonCode = {code:"KeyW"};
downButtonCode = {code:"KeyS"};
leftButtonCode = {code:"KeyA"};
rightButtonCode = {code:"KeyD"};
startButtonCode = {code:"Enter"};
