"use strict";
setCustomFileSector("elven-uvtc");
EssentialSounds.push(
    getFile("energy.mp3",FileTypes.Sound),
    getFile("energy-reverse.mp3",FileTypes.Sound),
    getFile("reverse-click.mp3",FileTypes.Sound),
    getFile("damage.mp3",FileTypes.Sound),
    getFile("heal.mp3",FileTypes.Sound),
    getFile("text-sound.mp3",FileTypes.Sound)
);
NonEssentialSounds.push();
ImagePaths.push(
    getFile("card-test.png",FileTypes.BackgroundImage),
    getFile("deck-background.png",FileTypes.BackgroundImage),
    getFile("ui/card-icons.png",FileTypes.Image),
    getFile("ui/status-roll.png",FileTypes.Image),
    getFile("world-tileset.png",FileTypes.Image),
    getFile("character-sprite.png",FileTypes.Image),
    getFile("footsteps.png",FileTypes.Image),
);
